GET http://127.0.0.1:8000/api/v1/alumno
Accept: application/json

### Registrar alumnos
POST http://127.0.0.1:8000/api/v1/alumno
Accept: application/json
Content-Type: application/json
Authorization: Bearer 22|rdOw8wVdYNQJ3GR57INhQJ8FadvHDnWUIX0JqlaE

{
    
    "alu_nom": "pietro",
    "alu_app": "mungia ",
    "alu_apm": "calixto",
    "alu_fnac": "10/10/2024",
    "alu_tipo_doc": "DNI",
    "alu_nmr_doc": 30303030,
    "alu_pais" : "Peru",
    "alu_departamento": "Pasco",
    "alu_provincia": "Pasco",
    "alu_distrito": "Huariaca",    
    "alu_sexo": "Masculino",    
    "alu_nom_madre": "Isidora",
    "alu_app_madre": "Castañeda",
    "alu_apm_madre": "Yacolca",
    "alu_tipo_doc_madre": "DNI",
    "alu_dni_madre": 23661089,
    "alu_civil_madre": "casada",    
    "alu_nom_padre": "Lorenzo",
    "alu_app_padre": "Cordova",
    "alu_apm_padre": "Garcia",
    "alu_tipo_doc_padre": "DNI",
    "alu_dni_padre": 69105877,   
    "alu_civil_padre": "casado",
    "apoderado_id": 8
}

### Actualizar registro de alumno
PATCH http://127.0.0.1:8000/api/v1/alumno/4
Accept: application/json
Content-Type: application/json

{
    "alu_foto": "foto",
    "alu_nom": "Juan Luis",
    "alu_app": "Gonzalez",
    "alu_apm": "Guerra",
    "alu_fnac": "20/07/86",
    "alu_tipo_doc": "DNI",
    "alu_nmr_doc": 44070633,
    "alu_grado": "Quinto",
    "alu_pais" : "Peru",
    "alu_departamento": "Pasco",
    "alu_provincia": "Pasco",
    "alu_distrito": "Huariaca",
    "alu_cert_discapacidad": "No",
    "alu_tipo_discapacidad": "Ninguna",
    "alu_nmr_hermanos": 4,
    "alu_lugar_ocupa": 3,
    "alu_sexo": "Masculino",
    "alu_lengua_materna": "Español",
    "alu_lengua_materna2": "ninguna",
    "alu_tipo_sangre": "OH",
    "alu_nacimiento_registrado": "20/07/86",
    "alu_religion": "Evangelico",
    "alu_nom_madre": "Isidora",
    "alu_app_madre": "Castañeda",
    "alu_apm_madre": "Yacolca",
    "alu_tipo_doc_madre": "DNI",
    "alu_dni_madre": 44070637,
    "alu_civil_madre": "casada",
    "alu_vive_madre": "Si",
    "alu_fnca_madre": "06/04/52",
    "alu_vive_con_este_madre": "Si",
    "alu_grado_inst_madre": "Secundaria",
    "alu_ocupacion_madre": "Ama de casa",
    "alu_religion_madre": "Evangelica",
    "alu_nom_padre": "Lorenzo",
    "alu_app_padre": "Cordova",
    "alu_apm_padre": "Garcia",
    "alu_tipo_doc_padre": "DNI",
    "alu_dni_padre": 44070639,
    "alu_vive_padre": "Si",
    "alu_fnca_padre": "30/08/52",
    "alu_vive_con_este_padre": "Si",
    "alu_grado_inst_padre": "Superior",
    "alu_ocupacion_padre": "Teconico Enfermero",
    "alu_religion_padre": "Evengelico",
    "alu_civil_padre": "casado",
    "apoderado_id": 3
}
### ver detalle de alumno
GET http://127.0.0.1:8000/api/v1/alumno/16
Accept: application/json

### Eliminar registro de alumno
DELETE http://127.0.0.1:8000/api/v1/alumno/3
Accept: application/json
