GET http://127.0.0.1:8000/api/v1/apoderado/
Accept: application/json

### Registrar apoderado
POST http://127.0.0.1:8000/api/v1/apoderado
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|qvfVd4UdY62Xl3BEaDSijiCMEdOvPmQqARa2jwr4

{
    "apo_nom": "marcos",
    "apo_app": "cantiruin",
    "apo_apm": "solano",
    "apo_dni": 22233167,
    "apo_telf": "958788853",
    "apo_dir": "PInos",
    "apo_fnac": "15/12/59",
    "apo_vinculo": "Abuelo",
    "apo_grado_inst": "Superior",
    "apo_estado": 1
}
### para modificar datos de apoderado
PATCH http://127.0.0.1:8000/api/v1/apoderado/1
Accept: application/json
Content-Type: application/json

{
    "apo_nom": "Benzema",
    "apo_app": "Italini",
    "apo_apm": "Angulo",
    "apo_dni": 80078569,
    "apo_telf": "958788856",
    "apo_dir": "Alamos",
    "apo_fnac": "15/12/59",
    "apo_vinculo": "Tio",
    "apo_grado_inst": "Superior"    
}
### para eliminar registro de apoderado
DELETE http://127.0.0.1:8000/api/v1/apoderado/3
Accept: application/json

