GET http://127.0.0.1:8000/api/v1/departamento
Accept: application/json
Content-Type: application/json

###Registrar departamento
POST http://127.0.0.1:8000/api/v1/departamento
Accept: application/json
Content-Type: application/json

{
    "depa_nom": "lauricocha"    
}

### Modificar Departamento
PATCH http://127.0.0.1:8000/api/v1/departamento/1
Accept: application/json
Content-Type: application/json

{
    "depa_nom": "Cerro de Pasco"
}

### Eliminar departamento
DELETE http://127.0.0.1:8000/api/v1/departamento/1
Accept: application/json

