GET http://127.0.0.1:8000/api/v1/notacurso
Accept: application/json
Content-Type: application/json

###Registrar notacurso
POST http://127.0.0.1:8000/api/v1/notacurso
Accept: application/json
Content-Type: application/json

{
    "notas": 9,
    "curso_id": 1,
    "obs": "alumno aplicado",
    "profesor_id": 1
}

### Modificar notacurso
PATCH http://127.0.0.1:8000/api/v1/notacurso/3
Accept: application/json
Content-Type: application/json

{
    "notas": 19.32,
    "curso_id": 1,
    "obs": "alumno aplicado",
    "profesor_id": 1
}

### Eliminar notacurso
DELETE http://127.0.0.1:8000/api/v1/notacurso/3
Accept: application/json