GET http://127.0.0.1:8000/api/v1/profesor
Accept: application/json
Content-Type: application/json

###Registrar profesor
POST http://127.0.0.1:8000/api/v1/profesor
Accept: application/json
Content-Type: application/json

{
    "user_id": 1,
    "pro_nom": "Hobbes",
    "pro_app": "Estrella",
    "pro_apm": "Cordova",
    "pro_dire": "Jr los pinos",
    "pro_telf": "985563365",
    "pro_correo": "profersor@mail.com",
    "pro_sexo": "masculino",
    "pro_dni": 25128118,
    "pro_grado_instruccion": "superior",
    "pro_especialidad": "Trigonometria",
    "pro_pais": "peru",
    "pro_fnac": "21/02/89",
    "pro_distrito": "huanuco",
    "pro_estado": 1
}

### Modificar profesor
PATCH http://127.0.0.1:8000/api/v1/profesor/1
Accept: application/json
Content-Type: application/json

{
    "pro_nom": "Hipolito",
    "pro_app": "Berrospi",
    "pro_apm": "Calderon",
    "pro_dire": "Jr los pinos",
    "pro_telf": "985563365",
    "pro_sexo": "masculino",
    "pro_dni": 45847867,
    "pro_grado_instruccion": "superior",
    "pro_especialidad": "matematias",
    "pro_pais": "peru",
    "pro_fnac": "21/02/89",
    "pro_distrito": "huanuco"
}

### Eliminar profesor
DELETE http://127.0.0.1:8000/api/v1/profesor/6
Accept: application/json