GET http://127.0.0.1:8000/api/v1/user
Accept: application/json

###registrar usuario
POST http://127.0.0.1:8000/api/v1/user
Accept: application/json
Content-Type: application/json

{
    "name": "Usuario 2",
    "usu_dni": 47741712,
    "email": "miher@mail.com",
    "email_verified_at": "",
    "usu_user": "miher",
    "password": "miher123456",    
    "usu_dir": "alamos",
    "usu_telf": 996041308,
    "profesor_id": "1",
    "tipousuario_id": "3",
    "alumno_id": "1"
}

###Modificar usuarios
PATCH http://127.0.0.1:8000/api/v1/user/4
Accept: application/json
Content-Type: application/json

{
    "name": "Herder Mijail",
    "usu_dni": 98565432,
    "email": "miher@mail.com",
    "email_verified_at": "",
    "usu_user": "miher",
    "password": "miher123456",    
    "usu_dir": "alamos",
    "usu_telf": 996041302,
    "profesor_id": 5,
    "tipousuario_id": 3,
    "alumno_id": 1
}

###Eliminar Usuarios
DELETE http://127.0.0.1:8000/api/v1/user/5
Accept: application/json
